config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :products
  
  resource :cart, only: :show do
    collection do
          get 'order'
    end
  end

  post '/carts/add_product', to: 'carts#add', as: 'add_to_cart'

  match '/send_mail', to: 'carts#send_mail', via: 'post'
  resources :accounts
  root 'products#index'
  #resources :galleries
  #resources :pictures
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :products
  belongs_to :account
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :cart_find
  before_action :total_price_of_products
  
  def show
  end
  
  def add
    @products_in_cart << Product.find(params[:product_id])
  end
  
  def order
  end

  def send_mail
    if OrderMailer.order_email(current_user.email)
      redirect_to products_path
      OrderMailer.order_email(current_user.email).deliver_later
      @products_in_cart.clear
      flash[:success] = t('order_created')
    else
      render 'order'
    end
  end
  
  private

  def cart_find
    @products_in_cart = Cart.includes(:products).find(session[:cart_id]).products || Cart.create(:cart_id => params[:id])
  end

  def total_price_of_products
    @total_sum = cart_find.sum(:price)
  end
end

app/views/carts/add.js.haml
alert('Successfully added to cart!')

app/views/carts/order.html.haml
.page-content-order
  %h1= t('order_title')
  %table.table.table-hover
    - @products_in_cart.each do |product|
      %tr
        %td= product.name
        %td= product.description
        %td= product.price
  %h3
    .sum-total
      = t('total_sum_is')
      %b
        = @total_sum

  = button_to 'Send', send_mail_path, method: :post, class: 'btn btn-success'
  %br
  = link_to t('back'), cart_path, class: 'btn btn-default'

app/views/carts/order.js.haml
alert('Order successfull')

app/views/carts/show.html.haml
.page-content-cart
  .page-header
    %h1= t('index.cart') 
    
    %table.table.table-hover
      - @products_in_cart.each do |product|
        %tr
          %td= product.name
          %td= product.description
          %td= product.price
          %td= link_to t('show'), product, class: 'btn btn-primary'
          %td= link_to t('edit'), edit_product_path(product), class: 'btn btn-warning'
          %td= link_to t('delete'), product, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger'
  %p
    = link_to t('order'), order_cart_path, class: 'btn btn-default'
  %p
    = link_to t('back'), products_path, class: 'btn btn-default'