config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :products
  
  resource :cart, only: :show do
    collection do
          get 'order'
    end
  end

  post '/carts/add_product', to: 'carts#add', as: 'add_to_cart'

  match '/send_mail', to: 'carts#send_mail', via: 'post'
  resources :accounts
  root 'products#index'
  #resources :galleries
  #resources :pictures
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :cart

  validates :name, presence: true, allow_blank: false
  validates :price,
            presence: true,
            allow_blank: false,
            numericality: { greater_than: 0,
                            message: 'must be grater then 0' }
  validates :description,
            presence: false,
            allow_blank: true

  has_attached_file :photo,
                    styles: { medium: '300x300>', thumb: '100x100>' },
                    default_url: ':style/missing.png'
  #                 storage: :cloudinary

  # validates_attachment_content_type :photo, content_type: %r{/\Aimage\/.*\Z/}
  validates_attachment :photo,
                       content_type: { content_type: ['image/jpeg',
                                                      'image/gif',
                                                      'image/png'] }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_product, only: [:show, :edit, :update, :destroy, :patch]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = 'Produt created!!!'
      redirect_to products_path
    else
      render 'new'
    end
  end

  def update
    if @product.update(product_params)
      flash[:info] = 'Product was successfully updated'
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    flash[:danger] = "You have destroyed product #{@product.name}"
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :photo)
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def product_list_partial_name
    @products.empty? ? 'empty' : 'list'
  end
  
end

app/views/products/_empty.html.haml
%h1= t('empty')
%br
= image_tag("giphy.gif")

%br
= link_to t('create_product'), new_product_path, class: 'btn btn-default'
= link_to t('all_accounts'), accounts_path, class: 'btn btn-info'  

app/views/products/_form.html.haml
= form_for @product, url: products_path, html: { multipart: true }  do |f|
  - if @product.errors.any?
    %div#error_explanation
      = error_messages_for(@product)
  .form-group
    = f.label :name
    %br
    = f.text_field :name
  .form-group
    = f.label :description
    %br
    = f.text_field :description
  .form-group
    = f.label :price
    %br
    = f.number_field :price
  .form-group
    = f.label :photo
    %br
    = f.file_field :photo
  .actions
    = f.submit
  

app/views/products/_list.html.haml
%h1= t('title-products')

%table.table.table-hover
  - @products.each do |product|
    %tr
      %td
        = image_tag product.photo.url(:thumb), class: 'image_zoom'
      %td
        %b
          = product.name
      %td= product.description
      %td= product.price
      %td= button_to t('add_to_cart'), add_to_cart_path(product_id: product.id), remote: true, class: 'btn btn-success'
      %td= link_to t('show'), product, class: 'btn btn-primary'
      %td= link_to t('edit'), edit_product_path(product), class: 'btn btn-warning'
      %td= link_to t('delete'), product, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger'
      %br
= link_to t('create_product'), new_product_path, class: 'btn btn-default'
= link_to t('all_accounts'), accounts_path, class: 'btn btn-info'  

app/views/products/edit.html.haml
.page-content
  %h1
    Edit
  = form_for @product, method: :patch, html: { multipart: true }  do |f|
    - if @product.errors.any?
      %div#error_explanation
        = error_messages_for(@product)
    .form-group
      = f.label :name
      %br
      = f.text_field :name
    .form-group
      = f.label :description
      %br
      = f.text_field :description
    .form-group
      = f.label :price
      %br
      = f.number_field :price
    .form-group
      = f.label :photo
      %br
      = f.file_field :photo
    .actions
      = f.submit
  
  = link_to t('show'), @product, class:'btn btn-default' |
  = link_to t('Back'), products_path, class:'btn btn-default'

app/views/products/index.html.haml
.index-products
  = render product_list_partial_name

app/views/products/new.html.haml
.page-content
  %h1
    New Product

  = render 'form'

  = link_to t('back'), products_path, class: 'btn btn-default'

app/views/products/show.html.haml
.page-content
  .page-header
    %h1= @product.name
  .panel.panel-default
    .panel-heading
      %h3.panel-title
        %b
          = Product.human_attribute_name(:description)
    .panel-body
      = @product.description
    .panel-heading
      %h3.panel-title
        %b
          image
    .panel-body
      = image_tag @product.photo.url(:medium)
  %ul.list-group
    %li.list-group-item
      %span.badge
        = @product.price
      %b
        = Product.human_attribute_name(:price)
  = link_to t('back'), products_path, class: 'btn btn-default'
  = link_to t('delete'), @product, method: :delete, class: 'btn btn-danger'


 