config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :products
  
  resource :cart, only: :show do
    collection do
          get 'order'
    end
  end

  post '/carts/add_product', to: 'carts#add', as: 'add_to_cart'

  match '/send_mail', to: 'carts#send_mail', via: 'post'
  resources :accounts
  root 'products#index'
  #resources :galleries
  #resources :pictures
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_one :cart
  has_many :friendships
  has_many :friends, through: :friendships,
                     dependent: :destroy
  belongs_to :user

  validates :name, presence: true, allow_blank: false, format: { with: /(?!^\d+\z)\A.+\z/, message: "can't consists of only digits" }, length: { in: 8..20 }
  validates :age, presence: true, allow_blank: false, inclusion: { in: 18..100, message: 'only from 18 to 100' }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :user_admin?
  before_action :authorize_admin, except: :new
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = Account.all.order(age: :asc)
  end


  def show
  end


  def new
    @account = Account.new
  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      AccountMailer.welcome_email(@account).deliver_later
      redirect_to accounts_path
      flash[:success] = "Account #{@account.name} created!!!"
    else
      render 'new'
    end
  end

  def update
    if @account.update(account_params)
      flash[:info] = "Account #{@account.name} updated!!!"
      redirect_to accounts_path
    else
      render 'new'
    end
  end

  def destroy
    @account.destroy
    flash[:danger] = "Account #{@account.name} deleted!"
    redirect_to accounts_path
  end

  private

    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:name, :age)
    end
    
end

app/helpers/accounts_helper.rb
module AccountsHelper
#    def bootstrap_class_for flash_type
#      { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
#    end
#
  #def flash_messages(opts = {})
  #  flash.each do |msg_type, message|
  #    concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
  #             concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
  #             concat message 
  #           end)
  #  end
  #  nil
  #end
end

app/views/accounts/_form.html.haml
.account-new
  = form_for(@account) do |f|
    - if @account.errors.any?
      %div#error_explanation
        = error_messages_for(@account)
    .form-group
      = f.label :name
      %br
      = f.text_field :name
    .form-group
      = f.label :age
      %br
      = f.text_field :age
    .actions
      = f.submit

app/views/accounts/edit.html.haml
.account-new
  %h1
    = t('edit_account')

  = render 'form'

  = link_to t('back'), accounts_path, class: "btn btn-info"
  = link_to t('show'), @account, class: "btn btn-success"

app/views/accounts/index.html.haml
.page-content-accounts
  %h1
    =t('index.title')
    =image_tag "https://media.giphy.com/media/3o7ablBxBULsBGyeCA/giphy.gif" 

  %table.table.table-hover
    %thead
      %tr
        %th= Account.human_attribute_name(:name)
        %th= Account.human_attribute_name(:age)
        %tbody
          - @accounts.each do |account|
            %tr
              %td= account.name
              %td= account.age
              %td= link_to t('show'), account, class: 'btn btn-primary'
              %td= link_to t('edit'), edit_account_path(account), class: 'btn btn-warning'
              %td= link_to t('delete'), account, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
              %br

  = link_to t('new_account'), new_account_path, class: 'btn btn-success'
  = link_to t('all_products'), products_path, class: 'btn btn-success'

app/views/accounts/new.html.haml
.account-new
  %h1
    = t('new_account')

  = render 'form'

  = link_to t('back'), accounts_path, class: 'btn btn-default'

app/views/accounts/show.html.haml
.page-content-accounts
  %h1
    = t('details_of')
    = "#{@account.name}"
  .panel.panel-default
    .panel-heading
      %h3.panel-title
        %b
          = Account.human_attribute_name(:name)
    .panel-body
      = @account.name
    .panel-heading
      %h3.panel-title
        %b
          = Account.human_attribute_name(:age)
    .panel-body
      = @account.age


  /= link_to 'Cart', cart
  = link_to t('back'), accounts_path, class: "btn btn-success"
  |
  = link_to t('edit'), edit_account_path(@account), class: "btn btn-success"
  |
  = link_to t('cart'), cart_path(@account.id), class: 'btn btn-default'